# Directory where input imputed filesets are.
# No trailing / is required.
directory: .

outputs: # Comment out any line with outputs you don't want
  - stat_report # A report of imputation quality
  - vcf_bycohort # Bgzipped VCF files for each cohort
  - vcf_merged # A bgzipped VCF with all cohorts
#  - bgen_bycohort # Binary oxford filesets for each cohort
#  - bgen_merged # A binary oxford fileset with all cohorts
  - plink_bycohort # Binary plink filesets for each cohort
  - plink_merged # A binary plink fileset with all cohorts

# Select chromosomes you want to analyse and merge
#  separate ranges with ":" and listed chromosomes
#  with ","
#  You can put both in the same string.
chroms: "1:22"

# QC Parameters for filtering and analysis
qc:
  # MAF Cutoff between common and rare
  maf: 0.01
  # Rsq to use with common variants
  rsq: 0.8
  # Rsq to use with rare variants (set to NA to use rsq as hard cutoff)
  rsq2: NA
  # Number of SNPs of each type (Imputed, Typed) to sample for figures
  sampsize: 100000


# filename of samples to include
include_samp:

# filename of samples to exclude
exclude_samp:

# --keep accepts a space/tab-delimited text file with
# family IDs in the first column and within-family IDs
# in the second column, and removes all unlisted samples
# from the current analysis. --remove does the same for
# all listed samples.

# filename of sample renaming mapping file:
rename:
#  automap:

