# Directory where input plink filesets are.
# No trailing / is required.
directory: .

# Select chromosomes you want to analyse and merge
#  separate ranges with ":" and listed chromosomes
#  with ","
#  You can put both in the same string.
chroms: "1:22"

# QC Parameters for filtering and analysis
qc:
  # MAF Cutoff between common and rare
  maf: 0.01
  # Rsq to use with common variants
  rsq: 0.3
  # Rsq to use with rare variants (set to NA to use rsq as hard cutoff)
  rsq2: 0.8
  # Number of SNPs of each type (Imputed, Typed) to sample for figures
  sampsize: 100000


# filename of samples to include (plink --keep)
include_samp:

# filename of samples to exclude (plink --remove)
exclude_samp:

# --keep accepts a space/tab-delimited text file with
# family IDs in the first column and within-family IDs
# in the second column, and removes all unlisted samples
# from the current analysis. --remove does the same for
# all listed samples.

# Automatically added settings
